name: Build Mac App with PyInstaller

on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'Test Build Tags'
jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Install Python3 & Dependicies
      run:  |
        brew reinstall python@3.7
        brew reinstall --build-bottle sdl2 sdl2_image sdl2_ttf sdl2_mixer
        pip3 install --upgrade pip wheel setuptools
        pip3 install Cython==0.29.10
        pip3 install -r ${{ github.workspace }}/requirements.txt
        
    - name: Package Application
      run:  |
        pyinstaller --clean -y --dist ./dist/mac --workpath /tmp --windowed ${{ github.workspace }}/PhoenixAnistream.spec
        cd dist
        pushd mac
        hdiutil create ./PhoenixAnistream.dmg -srcfolder PhoenixAnistream.app -ov
        popd
        ls

    - uses: actions/upload-artifact@v2
      with:
        name: PhoenixAnistreamMacBuild
        path: dist/PhoenixAnistream.app
