name: Build Mac App with PyInstaller

on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'Test Build Tags'

jobs:
  build:

    runs-on: macOS-10.14
    
    steps:
    - name: Setting Up Python3
      run: |
        brew install python3
    
    - name: Setting Up Brewing Installations
      run: |
        brew reinstall --build-from-source sdl2 sdl2_image sdl2_ttf sdl2_mixer

    - name: Pip Downloads
      run: |
        pip3 install Cython==0.29.28
        pip3 install -U kivy
        pip3 install -U pyinstaller
        ls
        pip3 instal -r requirementsMac.txt
    
    - name: Pyinstaller Build
      run: |
        pyinstaller --clean -y --dist ./dist/mac --workpath /tmp buildM.spec 
