name: Build Mac App with PyInstaller

on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'Test Build Tags'

jobs:
  build:

    runs-on: macOS-10.14
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Building Macports
      run: |
        ls
        curl -O https://distfiles.macports.org/MacPorts/MacPorts-2.7.2.tar.bz2
        tar xf MacPorts-2.7.2.tar.bz2
        cd MacPorts-2.7.2/
        ./configure
        make
        sudo make install
    
    - name: Setting Up Python3
      run: |
        brew install python3
    
    - name: Setting Up Brewing Installations
      run: |
        brew reinstall --build-from-source sdl2 sdl2_image sdl2_ttf sdl2_mixer

    - name: Pip Downloads
      run: |
        pip3 install Cython==0.29.28
        pip3 install -U kivy
        pip3 install -U pyinstaller
        pip3 install -r requirementsMac.txt
    
    - name: Pyinstaller Build
      run: |
        pyinstaller --clean -y --dist ./dist/mac --workpath /tmp buildM.spec 
