name: Build GUI exe with Pyinstaller

on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'test build tags'
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Package Application
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: .

    - name: Copy Resource & UI File
      run:  |
        Xcopy /E /I resources\ dist\windows
        copy /a /y /v AniApp.kv dist\windows

    - uses: actions/upload-artifact@v2
      with:
        name: PhoenixAnistream
        path: dist/windows
