name: Build Mac App with PyInstaller using Old Windows Build

on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'Test Build Tags'
jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/download-artifact@v2
      with:
        name: PhoenixAnistreamWindowsBuild
