name: Build Mac App with PyInstaller

on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'Test Build Tags'

jobs:
  build:

    runs-on: macos-latest
    
    steps:
    - name: Set Brews
      run: |
        brew install python3
        brew reinstall --build-from-source sdl2 sdl2_image sdl2_ttf sdl2_mixer

    - name: MacPorts
      uses: keepitsimpletech/actions/setup-macports@setup-macports/releases/v1

