name: Build Mac App with PyInstaller using Old Windows Build

on:
  workflow_dispatch:
    inputs:
      actionDownloadLink:
        required: true
        description: 'Windows Build Link'
jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: Download the Artifact From Windows Build
      run:  |
        echo "Link ${{ github.event.inputs.actionDownloadLink }}"
        mkdir dist
        curl ${{ github.event.inputs.actionDownloadLink }} -o "dist/PhoenixAnistreamWindowsBuild.zip"
        ls
        cd dist
        ls
