name: Build GUI exe with Pyinstaller

on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'test build tags'
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Package Application
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: .

    - name: Copy Resource & UI File
      run:  |
        cp -R ${{ github.workspace }}/resources dist/windows/PhoenixAnistream
        cp  ${{ github.workspace }}/AniApp.kv dist/windows/PhoenixAnistream

    - uses: actions/upload-artifact@v2
      with:
        name: PhoenixAnistreamWindowsBuild
        path: dist/windows
